name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  Upload-To-EC2:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          passphrase: ${{ secrets.EC2_PASSPHRASE }}
          script: |
            # Killing existing Node.js server
            PID=$(sudo lsof -t -i:5500)
            if [ ! -z "$PID" ]; then
              sudo kill -9 $PID
              if [ $? -ne 0 ]; then
                echo "Failed to kill process with PID $PID"
                exit 1
              fi
            fi

            # Remove previously Cloned Repo
            rm -rf Hybrid-Haven-Web
            if [ $? -ne 0 ]; then
              echo "Failed to remove Hybrid-Haven-Web directory"
              exit 1
            fi

            # Clone Our repository
            git clone https://github.com/Umang-Vadadoriya-BBD/Hybrid-Haven-Web.git
            if [ $? -ne 0 ]; then
              echo "Failed to clone repository"
              exit 1
            fi

            # Start Node.js server In No HangUp Mode
            sudo nohup node server.js > output.log 2>&1 &
            if [ $? -ne 0 ]; then
              echo "Failed to start Node.js server"
              exit 1
            fi